### ISSUE TITLE
Why is the mod_config a requirement ?

### ISSUE THREAD

**Issue by zelding** [slvn/isaac-destination-indicator#1]
All you do is require it in the first line, than do nothing with it.
Does is do something non-obvious ?

**Comment by slvn** [comment]
Good question.

It allows me to use the method declared [here](https://github.com/slvn/isaac-destination-indicator/blob/main/src/types/ScreenHelper.d.ts#L4) in order to get the offset of the HUD setup in mod config. Isaac API does not give us access to the offset settings so mod config has one so every mod can use it, this is what I am doing here like a bunch of other mods.

Now, if I had time, I would work on a better system, not making mod config a hard dependency but try to use it at runtime and if not available, fallback on another system like the one from planetarium chances where users can use `j` and `k` touch to set it up manually. Unfortunately, I didn't find the time to work on this but it's in my mental TODO.

**Comment by slvn** [comment]
@zelding I removed the hard dependency and just checking if available at runtime.
I'm not providing any other alternative for offset as of now.
